# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Book-Finder-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'RxSwift', '6.5.0'
pod 'RxCocoa', '6.5.0'
pod 'SnapKit', '~> 5.0.0'
pod 'Alamofire'

  # Pods for Book-Finder-App

  target 'Book-Finder-AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Book-Finder-AppUITests' do
    # Pods for testing
  end

end
